export {TelaInicial as ScreenTelaInicial} from './TelaInicial'
export {Receitas as ScreenReceitas} from './Receitas'
export {Perfil as ScreenPerfil} from './Perfil'
export {Mensagem as Mensagem} from './Mensagem'
export {CadMensagem as ScreenCadMensagem} from './CadMensagem'
export {Login as ScreenLogin} from './Login'
export {Register as ScreenRegister} from './Register'
export {Camera as ScreenCamera} from './Camera'
export { Imagens as ScreenImagens } from './Imagens'
export { QrCode as ScreenQrCode } from './QrCode'