export {TelaInicial as ScreenTelaInicial} from './TelaInicial'
export {Receitas as ScreenReceitas} from './Receitas'
export {Perfil as ScreenPerfil} from './Perfil'
export {Mensagem as ScreenMensagem} from './Mensagem'
export {CadMensagem as ScreenCadMensagem} from './CadMensagem'
export {Login as ScreenLogin} from './Login'
export {Register as ScreenRegister} from './Register'