export {TelaInicial as ScreenTelaInicial} from './TelaInicial'
export {Geral as ScreenGeral} from './Geral'
export {Perfil as ScreenPerfil} from './Perfil'
export {Login as ScreenLogin} from './Login'
export {Register as ScreenRegister} from './Register'